name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Add EC2 host to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

    - name: Install dependencies for frontend
      run: |
        yarn install
      working-directory: client

    - name: Install dependencies for backend
      run: |
        yarn install
      working-directory: server

    - name: Build frontend
      run: |
        yarn build
      working-directory: client

    - name: Upload frontend to S3
      run: |
        aws s3 sync ./client/dist s3://esaote-cloud-gallery --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Deploy to EC2
      run: |
        ssh ubuntu@${{ secrets.EC2_IP }} "cd Esaote_CloudImageGallery/server && yarn install && yarn start"
      env:
        EC2_IP: ${{ secrets.EC2_IP }}
