name: Deploy on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/temp_key  # Scrivi la chiave in un file temporaneo
          sed -i 's/\r//' ~/.ssh/temp_key        # Rimuovi i caratteri di ritorno a capo (CR)
          mv ~/.ssh/temp_key ~/.ssh/id_rsa       # Sposta la chiave modificata nel file finale
          chmod 600 ~/.ssh/id_rsa               # Imposta i permessi sulla chiave
          ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts  # Aggiungi l'IP del server EC2 ai known hosts

      - name: Deploy Backend to EC2
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            cd Esaote_CloudImageGallery/server
            git pull origin main
            yarn install
            yarn start
          EOF
        env:
          EC2_IP: ${{ secrets.EC2_IP }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
